### ISSUE TITLE
small typo in description

### ISSUE THREAD

**Issue by jastuccio** [ixkaito/wocker-dockerfile#7]
The description says "The Dockerfile for _"Worcker"_  I think it sould read **"Wocker"**.  I cloned the repo and corrected it.  When I tried to make a pull request Github says my clone is identical to master.  Maybe it doesn't compare descriptions?  Thank you for creating wocker.  I have had some trouble getting  my WP docker environment setup and decided to give wocker a try.

**Comment by ixkaito** [comment]
Fixed. Thanks!

> Maybe it doesn't compare descriptions?

I think so.
